### ISSUE TITLE
Naive Question.

### ISSUE THREAD

**Issue by shersoni610** [autodistill/autodistill-metaclip#1]
Hello,

Isn't this code using Open-AI Clip and not meta-clip model? Can someone confirm?

Thanks

**Comment by capjamesg** [comment]
Hello @shersoni610! Thank you for opening this Issue, and apologies for the inconvenience. I'm not sure why we had OpenAI model code in there. I have just published a new release, `autodistill-metaclip==0.1.2` with the requisite code to use MetaCLIP. Let me know if you have any questions!
